import {
  Margherita,
  sixCheese,
  CheeseBurger,
  SmokyRanch,
  LittleItaly,
  CheeseTooppings,
  SpicyPepperoniRanch,
  SpicyPepperoni,
  ChickenRanch,
  ChickenBBQ,
  BreadSticks,
  CheeseSticks,
  SpicyRolls,
  ChickenRolls,
  TandooriWings,
  GrilledWings,
  ChickenPop,
  TandooriPop,
  Shrimps,
  Buffalo,
  Pepsi,
  Mirinda,
  Water
} from "../images.js";

export const navData = [
  [1, "Home", "/"],
  [2, "About", "/about"],
  [3, "Menu", "/menu"],
  [4, "Contact", "/contact"],
];

export const menu = [
  {
    id: 1,
    img: Margherita,
    title: "Margherita",
    details: "A traditional Margherita pizza with fresh mozzarella, basil, and tomatoes.",
    sprice: 80,
    mprice: 150,
    lprice: 180,
    ssize: "Small",
    msize: "Medium",
    lsize: "Large",
  },
  {
    id: 2,
    img: sixCheese,
    title: "Six Cheese",
    details: "A pizza loaded with six different cheeses for the ultimate cheesy experience.",
    sprice: 85,
    mprice: 130,
    lprice: 190,
    ssize: "Small",
    msize: "Medium",
    lsize: "Large",
  },
  {
    id: 3,
    img: CheeseBurger,
    title: "Cheese Burger",
    details:
      "All the flavors of a cheeseburger on a pizza, with plenty of cheese.",
      sprice: 90,
      mprice: 140,
      lprice: 200,
      ssize: "Small",
      msize: "Medium",
      lsize: "Large",
  },
  {
    id: 4,
    img: SmokyRanch,
    title: "Smoky Ranch",
    details:
      "Smoky flavors paired with a creamy ranch base for a unique taste.",
    sprice: 95,
    mprice: 150,
    lprice: 210,
    ssize: "Small",
    msize: "Medium",
    lsize: "Large",
  },
  {
    id: 5,
    img: LittleItaly,
    title: "Little Italy",
    details:
      "A pizza inspired by the flavors of Italy, with fresh tomatoes and basil.",
    sprice: 100,
    mprice: 160,
    lprice: 220,
    ssize: "Small",
    msize: "Medium",
    lsize: "Large",
  },
  {
    id: 6,
    img: SpicyPepperoni,
    title: "Spicy Pepperoni",
    details: "Pepperoni with a spicy twist, topped with a zesty ranch sauce.",
    sprice: 105,
    mprice: 170,
    lprice: 230,
    ssize: "Small",
    msize: "Medium",
    lsize: "Large",
  },
  {
    id: 7,
    img: ChickenRanch,
    title: "Chicken Ranch",
    details:
      "Tender chicken topped with a creamy ranch sauce and fresh vegetables.",
    sprice: 110,
    mprice: 180,
    lprice: 240,
    ssize: "Small",
    msize: "Medium",
    lsize: "Large",
  },
  {
    id: 8,
    img: Shrimps,
    title: "Shrimps",
    details:
      "Shrimps, Tomato, Onions, Green Pepper.",
    sprice: 115,
    mprice: 190,
    lprice: 260,
    ssize: "Small",
    msize: "Medium",
    lsize: "Large",
  },
  {
    id: 9,
    img: CheeseTooppings,
    title: "Cheese Tooppings",
    details:
      "A delightful combination of three cheeses with two of your favorite toppings",
    sprice: 120,
    mprice: 200,
    lprice: 260,
    ssize: "Small",
    msize: "Medium",
    lsize: "Large",
  },
  {
    id: 10,
    img: SpicyPepperoniRanch,
    title: "Spicy Pepperoni Ranch",
    details: "Pepperoni pizza with a kick, combined with creamy ranch sauce.",
    sprice: 125,
    mprice: 210,
    lprice: 270,
    ssize: "Small",
    msize: "Medium",
    lsize: "Large",
  },
  {
    id: 11,
    img: ChickenBBQ,
    title: "Chicken BBQ",
    details:
      "juicy chicken smothered in a tangy barbecue sauce. This pizza is topped with a blend of melted cheeses, red onions, and cilantro, offering a perfect balance of smoky, sweet, and zesty flavors.",
    sprice: 130,
    mprice: 220,
    lprice: 280,
    ssize: "Small",
    msize: "Medium",
    lsize: "Large",
    },
  {
    id: 12,
    img: Buffalo,
    title: "Buffalo Poppers",
    details: "Chicken Poppers,Beef Bacon, Onions, Jalapeno Pepper, Ranch Sauce with Buffalo Sauce Drizzled on top.",
    sprice: 170,
    mprice: 240,
    lprice: 300,
    ssize: "Small",
    msize: "Medium",
    lsize: "Large",
  },
  {
    id: 13,
    img: BreadSticks,
    title: "Bread Sticks",
    details: "Delicious oven - baked sticks. Served with BBQ Sauce.",
    price: 45,
  },
  {
    id: 14,
    img: CheeseSticks,
    title: "Cheese Sticks",
    details: "Fresh dough with a blend of Garlic Sauce and Mozzrella cheese, Served with BBQ Sauce.",
    price: 99,
  },
  {
    id: 15,
    img: SpicyRolls,
    title: "Spicy Pepperoni Ranch Rolls",
    details: "8 Rolls stuffed with Pepperoni, Jalapeno, Mozzarella Cheese and Ranch Sauce.",
    price: 145,
  },
  {
    id: 16,
    img: ChickenRolls,
    title: "Chicken Ranch Rolls",
    details: "8 Chicken Rolls stuffed with Mozzarella Cheese and Ranch Sauce.",
    price: 145,
  },
  {
    id: 17,
    img: TandooriWings,
    title: "Tandoori Wings",
    details: "Savory wings baked to the bone served with barbeque sauce.",
    price: 109,
  },
  {
    id: 18,
    img: GrilledWings,
    title: "Grilled Chicken Wings",
    details: "Savory wings baked to the bone served with barbeque sauce.",
    price: 115,
  },
  {
    id: 19,
    img: ChickenPop,
    title: "Chicken Poppers",
    details: "9 pieces of Tender all-white chicken breasts, breaded and oven baked, Served with Ranch Sauce.",
    price: 160,

  },
  {
    id: 20,
    img: TandooriPop,
    title: "Tandoori Poppers",
    details: "9 pieces of Tender all-white chicken breasts, breaded and oven baked, Served with Ranch Sauce.",
    price: 170,
  },
  {
    id: 21,
    img: Pepsi,
    title: "Pepsi",
    details: " ",
    price: 20,
  },
  {
    id: 22,
    img: Mirinda,
    title: "Mirinda",
    details: " ",
    price: 20,
  },
  {
    id: 23,
    img: Water,
    title: "Mineral Water",
    details: " ",
    price: 20,
  },
];
